#!/bin/bash

echo "🔧 Gorbagana Testnet Configuration for MetaMask"
echo "=============================================="
echo ""
echo "📋 Network Details to Add to MetaMask:"
echo "-----------------------------------"
echo "Network Name: Gorbagana Testnet"
echo "RPC URL: https://testnet-rpc.gorbagana.com"
echo "Chain ID: gorbagana-testnet"
echo "Currency Symbol: GOR"
echo "Block Explorer: https://explorer.gorbagana.com"
echo ""
echo "🎯 Steps to Add Network:"
echo "1. Open MetaMask extension"
echo "2. Click on Network dropdown (top center)"
echo "3. Click 'Add Network' or 'Custom RPC'"
echo "4. Fill in the details above"
echo "5. Save the network"
echo "6. Switch to Gorbagana Testnet"
echo ""
echo "💰 Get Test GOR Tokens:"
echo "Visit: https://faucet.gorbagana.com (if available)"
echo "Or contact Gorbagana team for testnet tokens"
echo ""
echo "🔄 After Setup:"
echo "1. Refresh your Gorbagana Plinko page"
echo "2. Connect wallet again"
echo "3. Sign the authentication message"
echo "4. You'll be redirected to the game!"